
site:
  origin: https://acme.org

rss:
  enabled: true
  title: Acme blog
  description: Latest news on web development
  collection: blog

collections:
  blog:
    include: [ posts/ ]
    require: [ title ]
    sort: date desc