
# Nue settings
site:
  view_transitions: true
  origin: https://nuejs.org

content:
  heading_ids: true
  sections: true
  wrap: wrap


meta:
  title: The UNIX of the Web
  description: Nue is a standards first web framework. It takes modern HTML, CSS, and JavaScript to their absolute peak.
  favicon: /img/favicon-small.png
  og: /img/og.png



