
# Nue settings
site:
  view_transitions: true
  origin: https://nuejs.org

content:
  heading_ids: true
  sections: true
  wrap: wrap


meta:
  title: The UNIX of the Web
  tagline: The UNIX of the Web
  title_template: %s / Nue
  description: Nue takes modern HTML, CSS, and JS to their absolute peak.
  favicon: /img/favicon-small.png
  og: /img/og.png

teaser:
  text: Nue 2.0 is out! →
  url: /blog/nue-2.0/
  tag: New

gh:
  url: https://github.com/nuejs/nue
  count: 8.8k

slack:
  url: //join.slack.com/t/nuejs/shared_invite/zt-2wf8ozu5i-N2Y9PA_D17weIWuN2QPOqQ

join:
  title: Up next: 3.0 with multi-site
  cta: Ping me
  desc:
    Get an email when the next major version with [multi-site development](/docs/roadmap) is ready