
# Nue settings
view_transitions: true
heading_ids: true
sections: true

# Content settings
title: The UNIX of the web
description: Nue is a standards-first framework pushing HTML, CSS, and JS to their absolute peak. You'll build apps lighter than a React button.
og: /img/standards-first.png
favicon: /img/logo.svg
