
meta:
  title_template: %s / Form & Function
  description: The new standard for web design and development

  # default author for blog entries
  author: Emma Bennet

site:
  origin: https://acme.org
  view_transitions: true

sitemap:
  enabled: true

content:
  sections: true

collections:
  blog:
    include: [ blog/ ]
    skip: [ skip ]
    sort: date desc

  design:
    include: [ docs/ ]
    tags: [ design ]
    sort: order

  dev:
    include: [ docs/ ]
    tags: [ dev ]
    sort: order


# custom additions
import_map:
  app: /@shared/app.js

server:
  db: db/app.db
  kv: db/kv.db
  reload: true

# use a central design system
design:
  central: true
  max_class_names: 2


exclude: [ svg/ ]