
site:
  view_transitions: true
  origin: https://acme.org

sitemap:
  enabled: true


content:
  sections: true

collections:
  blog:
    include: [ blog/ ]
    skip: [ draft, private ]
    sort: date desc


# custom additions
import_map:
  app: /@system/app.js

server:
  db: db/app.db
  kv: db/kv.db
  reload: true

# use a central design system
design:
  central: true
  max_class_names: 2