
site:
  view_transitions: true
  sitemap: true

content:
  sections: true

# custom additions
import_map:
  app: /@system/app.js

server:
  db: db/app.db
  kv: db/kv.db
  reload: true

# use a central design system
design:
  central: true
  max_class_names: 2