name: Repository nue page build
description: |
  Internal composite action to install dependencies, register the `nue` command, and build a Nue project.

inputs:
  root:
    description: |
      The root directory of the Nue project to build.
      This is passed to the `--root` option of the `nue build` command.
    default: '.'
    required: false

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v2

    - name: Install and link nue
      shell: bash
      run: |
        bun install
        cd packages/nuekit/
        bun link

    - name: Build Nue Project
      shell: bash
      run: nue build -pr "${{ inputs.root }}"
