name: Check Links

on:
  push:
    branches:
      - master
    paths:
      - '**/README.md'
      - 'packages/nuejs.org/**'
  pull_request:
    paths:
      - '**/README.md'
      - 'packages/nuejs.org/**'
  workflow_dispatch:

jobs:
  readme:
    if: ${{ github.repository_owner == 'nuejs' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check README links
        uses: lycheeverse/lychee-action@v2
        with:
          lycheeVersion: v0.16.1
          args: >
            --no-progress
            --include-fragments
            --exclude-path "node_modules"
            --exclude "localhost"
            --base "."
            --
            "**/README.md"
          token: ${{ secrets.GITHUB_TOKEN }}

  site:
    if: ${{ github.repository_owner == 'nuejs' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build docs
        uses: ./.github/workflows/repo/build-page
        with:
          root: packages/nuejs.org

      - name: Check site links
        uses: lycheeverse/lychee-action@v2
        with:
          lycheeVersion: v0.16.1
          args: >
            --no-progress
            --include-fragments
            --accept "403, 429, 503, 999"
            --remap "file:///@ https://nuejs.org/@"
            --remap "file:///todomvc https://nuejs.org/todomvc"
            --remap "file:///glow-demo https://nuejs.org/glow-demo"
            --exclude "404.html"
            packages/nuejs.org/.dist/prod/**/*.html
          token: ${{ secrets.GITHUB_TOKEN }}
